apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./wait-for mongo:27017 -- node .
          env:
            - name: DB_COLLECTION
              value: mybooks
            - name: DB_HOST
              value: mongo
            - name: DB_NAME
              value: books_db
            - name: DB_PORT
              value: "27017"
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "7002"
          image: mhjkeee/backend:2.0.0
          name: backend
          ports:
            - containerPort: 7002
          resources: {}
      restartPolicy: Always
status: {}
